//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI_Test__Playwright_ {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Constants {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Constants() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UI_Test__Playwright_.Constants", typeof(Constants).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&apos;add-to-cart-sauce-labs-backpack&apos;].
        /// </summary>
        internal static string backpackAddtoCartBtn {
            get {
                return ResourceManager.GetString("backpackAddtoCartBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&apos;back-to-products&apos;].
        /// </summary>
        internal static string backToHomeBtn {
            get {
                return ResourceManager.GetString("backToHomeBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&apos;add-to-cart-sauce-labs-bike-light&apos;].
        /// </summary>
        internal static string bikeAddtoCartBtn {
            get {
                return ResourceManager.GetString("bikeAddtoCartBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@class=&apos;cart_item&apos; and @data-test=&apos;inventory-item&apos;].
        /// </summary>
        internal static string cartItem {
            get {
                return ResourceManager.GetString("cartItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&apos;checkout&apos;].
        /// </summary>
        internal static string checkoutBtn {
            get {
                return ResourceManager.GetString("checkoutBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&apos;continue&apos;].
        /// </summary>
        internal static string continueBtn {
            get {
                return ResourceManager.GetString("continueBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&apos;continue-shopping&apos;].
        /// </summary>
        internal static string continueShoppingBtn {
            get {
                return ResourceManager.GetString("continueShoppingBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to secret_sauce.
        /// </summary>
        internal static string correctPassword {
            get {
                return ResourceManager.GetString("correctPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&apos;login_button_container&apos;]/div/form/div[3].
        /// </summary>
        internal static string errorMessageLocator {
            get {
                return ResourceManager.GetString("errorMessageLocator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Epic sadface: Username and password do not match any user in this service.
        /// </summary>
        internal static string errorMessageText {
            get {
                return ResourceManager.GetString("errorMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&apos;finish&apos;].
        /// </summary>
        internal static string finishBtn {
            get {
                return ResourceManager.GetString("finishBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&apos;first-name&apos;].
        /// </summary>
        internal static string firstNameInput {
            get {
                return ResourceManager.GetString("firstNameInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to incorrectPassword123.
        /// </summary>
        internal static string incorrectPassword {
            get {
                return ResourceManager.GetString("incorrectPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&apos;last-name&apos;].
        /// </summary>
        internal static string lastNameInput {
            get {
                return ResourceManager.GetString("lastNameInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&apos;login-button&apos;].
        /// </summary>
        internal static string loginButton {
            get {
                return ResourceManager.GetString("loginButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.saucedemo.com/.
        /// </summary>
        internal static string mainURL {
            get {
                return ResourceManager.GetString("mainURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&apos;password&apos;].
        /// </summary>
        internal static string passwordTextBox {
            get {
                return ResourceManager.GetString("passwordTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&apos;remove-sauce-labs-backpack&apos;].
        /// </summary>
        internal static string removeBackPackBtn {
            get {
                return ResourceManager.GetString("removeBackPackBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&apos;shopping_cart_container&apos;].
        /// </summary>
        internal static string shoppingCartIcon {
            get {
                return ResourceManager.GetString("shoppingCartIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to standard_user.
        /// </summary>
        internal static string standardUserName {
            get {
                return ResourceManager.GetString("standardUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&apos;user-name&apos;].
        /// </summary>
        internal static string userNameTextBox {
            get {
                return ResourceManager.GetString("userNameTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&apos;postal-code&apos;].
        /// </summary>
        internal static string zipCodeInput {
            get {
                return ResourceManager.GetString("zipCodeInput", resourceCulture);
            }
        }
    }
}
